### PR TITLE
Create 控物法.wy

### LINKED ISSUE #388: 使用變數作為鍵值
舉例來說

```
吾有一物。名之曰「甲」。
昔之「甲」之「「測試」」者。今百是矣。
吾有一言。曰「甲」。書之。
```
輸出：
```
{ '測試': 100 }
```

但是
```
吾有一言。曰「「測試」」。名之曰「鍵」。
吾有一物。名之曰「甲」。
昔之「甲」之「鍵」者。今百是矣。
吾有一言。曰「甲」。書之。
```
輸出：
```
{ NaN: 100 }
```

其中
```
昔之「甲」之「鍵」者。今百是矣。
```
編譯成了
```
甲[鍵 - 1] = 100
```

### PR DESCRIPTION
**Pull request by Fros1er**
Fixes #388 #541

### CODE REVIEW

**Comment by Fros1er** [comment]
By the way, changing to typescript is the better solution obviously.

**Comment by LingDong-** [comment]
Looks good, thanks!
Let's call it `格物.wy` after 格物致知. This way we can also add more object-related features into it in the future :)

**Comment by Fros1er** [comment]
Sounds great :)

**Comment by LingDong-** [comment]
👍

**Pull request merged**
