### PR TITLE
Add breadth-first search algorithm example

### PR DESCRIPTION
**Pull request by kevinjycui**
Implementing a [breadth-first search (BFS)](https://en.wikipedia.org/wiki/Breadth-first_search) or [廣度優先搜索](https://zh.wikipedia.org/wiki/%E5%B9%BF%E5%BA%A6%E4%BC%98%E5%85%88%E6%90%9C%E7%B4%A2) example
Calculates the shortest distance between two nodes on a cyclic bidirectional graph.
I'm not very good at the syntax so the format may need some fixing. Otherwise, it works.

### CODE REVIEW

**Comment by antfu** [comment]
Comments with prefix `批曰。` would be better. 
And for the failing test, could you help run `npm run test:update` and commit the snapshot? 

Besides that, it looks good to me. Thanks for the new example!

**Comment by kevinjycui** [comment]
I've committed the snapshot and fixed the comment format, though I left in the 「「」」format for multiline comments. Hope that's okay!

**Comment by kevinjycui** [comment]
I used the prefix `注曰。` instead since I felt that it fit better. Hope that's okay!

**Comment by LingDong-** [comment]
Awesome, thanks a lot for the new example!

**Pull request merged**
