### PR TITLE
feat(ide): compile for different target languages

### PR DESCRIPTION
**Pull request by antfu**
https://deploy-preview-546--wenyan-lang.netlify.com/ide

----

image

### CODE REVIEW

**Comment by LingDong-** [comment]
Woah let's not expose the button just yet, Python and Ruby transpilers are very broken right now :P

- Python has this scoping problem, where variables are default to local scope unless a `global xx` or `nonlocal xx` is placed at the beginning of a block (IMHO poor design haha). So I had to add a bunch of hacks that basically litters the code with `nonlocal` wherever possible. It did pass the examples, but I suspect I need to do some major rewrite to `PYCompiler` to make it more robust.

- Python also doesn't have an easy way to simulate namespaces within the same file (despite *Zen of Python* claiming namespaces are "one honking" good idea). One can use classes, but much of the syntax inside it has to change. So currently all the imported source code are just all concatenated togher. Two solutions: 1. Major rewrite. 2. Output separate files for each module, and have them just `import` each other.

- Ruby is wayyy behind and most of the new features are not added. The author of that transpiler seemed to have moved on...

Maybe we can comment out the button code for now, and when py and rb are more ready, uncomment them?

**Comment by antfu** [comment]
I do notice the incomplete to those languages which doing the migration of typescript. But somehow I just found out I kinda like the workflow to debug the parser/core in online IDE with `npm run dev:site` & `live-server` ;). The reason I bring this up is to better make them work better.

> Maybe we can comment out the button code for now, and when py and rb are more ready, uncomment them?

Oh, I think I have a good idea! Maybe we can have a url query string called `?experiment=true` or something to enable such features for developers who know what's going on without obstructing the beginners/normal users.

What do you think? :)

**Comment by LingDong-** [comment]
I think `?experiment=true` is one awesome idea!

**Comment by antfu** [comment]
Done!

**Comment by antfu** [comment]
Resolved. Please merge this before #551

**Pull request merged**
