### PR TITLE
Add eval function to stdlib

### PR DESCRIPTION
**Pull request by antfu**
This PR adds `eval` function to wenyan, which can run native code from strings.

```wenyan
吾嘗觀「「天地經」」之書。方悟「鑒」之義。

施「鑒」於「「1 + 1」」書之。
``` 

A fix for literal parsing is also included, line breaking will now be presented as `\n` in compiled code.

With this fix, we can also get rid of the `\` in 混沌經 example.

```
吾有一言。曰「「\
	物\
		之「名」言「李白」\
		之「字」言「太白」\
		之「號」言「青蓮」\
」」
```
```
吾有一言。曰「「
	物
		之「名」言「李白」
		之「字」言「太白」
		之「號」言「青蓮」
」」
```

### CODE REVIEW

**Comment by XingZiLong** [comment]
That’ll simplify most of my work :D

**Comment by LingDong-** [comment]
Nice! Thanks :)

**Comment by antfu** [comment]
> Is eval() function only work on JavaScript code or Wenyan code?

It works on the native target language. If you compile to js then it's Javascript code, if you compile it to python then it's python code and so on.

**Comment by XingZiLong** [comment]
Ah, I see.

**Pull request merged**
