### PR TITLE
Improve test writing experiences for devs

### PR DESCRIPTION
**Pull request by antfu**
Refer to: #487 

## Changes
- Make `hanzi2num` more clear and sperate `num2hanzi` and `hanzi2num` into different groups.
- Utils for stdlib testing.
- Stubs for `stdlib.calendar.test.js` and `stdlib.math.test.js`, should be fulfilled in the future.
- Set timezone to `UTC` for calendar testing

-----

The `stdlib.calender.test.js` currently looks like this:

```js
const { createTestUtil } = require("./utils");

const { expectOutput } = createTestUtil({
  prefix: "吾嘗觀「「曆法」」之書。",
  suffix: "書之"
});

describe("stdlib", () => {
  describe("calendar", () => {
    it("言彼之時刻", () => {
      expectOutput(
        "方悟「言彼之時刻」之義。施「言彼之時刻」於四千七百一十四",
        "丑初一刻三分三十四秒"
      );
    });

    it("言彼之日時", () => {
      expectOutput(
        "方悟「言彼之日時」之義。施「言彼之日時」於四千七百一十四",
        "西元一九六九年己酉年十一月二十四日辛巳日丑初一刻三分三十四秒"
      );
    });
  });
});
```

### CODE REVIEW

**Comment by statementreply** [comment]
I'm wondering whether it is possible to implement batch random testing for the math library. Maybe something like

```
const 算經 = compileLibrary("算經");

for (let i = 0; i < 10000; i++) {
  const x = Math.random() * Math.exp((Math.random() * 2 - 1) * 720);
  const jsResult = Math.log(x);
  const wyResult = 算經.對數(x);
  assert.ok(approxEqual(wyResult, jsResult, Number.EPSILON * 2, 0));
}
```

**Comment by antfu** [comment]
@statementreply I think it's possible. But I am not very sure if it's a good practice since the test will be unstable. Or we can use some seed-able random approach for that. I will do more research about random testing, please stay tuned. 

And I like the `compileLibrary` idea! Will try to implement something like that.

Thanks!

**Comment by statementreply** [comment]
@antfu I'm thinking about doing random testing on math lib locally. Maybe it's not a good idea for the workflow.

**Comment by antfu** [comment]
Merging now. If you come up with better ideas, feel free to raise up!

**Pull request merged**
