### PR TITLE
Add tests for math lib

### PR DESCRIPTION
**Pull request by statementreply**

### CODE REVIEW

**Comment by antfu** [comment]
Looks awesome!👍 Please keep it up!

**Comment by statementreply** [comment]
I've added tests for math lib APIs except the following:
- `冪`: The existing implementation doesn't work for large powers and will not pass tests.
- `浮點移位`
- `析浮點數`
- `取底除`
- `取整除`

`勾股求角` test failures will be resolved by #538.

**Comment by antfu** [comment]
Just for curious. How you do get those test cases? 😲

**Comment by statementreply** [comment]
> Just for curious. How you do get those test cases? 😲

- edge cases: `asin(1)`, `sqrt(0)`
- special cases: `log(0)`, `atan(Infinity)`
- tricky cases: `sin(Math.PI)` (shouldn't return zero!), `round(0.5 - Number.EPSILON * 0.25)` (Java <=6 got it wrong)
- random cases

**Comment by LingDong-** [comment]
Thanks so much for the tests!

**Pull request merged**
