### PR TITLE
Improve IDE2

### PR DESCRIPTION
**Pull request by antfu**
Preview: https://deploy-preview-535--wenyan-lang.netlify.com/ide2

- Proper right-align buttons
- Use icons for buttons
- Download renders
- Favicons for ide2/index (hand-drawn, hope you like them) 

image

### CODE REVIEW

**Comment by LingDong-** [comment]
👍Wow! The button icons look great (the favicon too), and I like how the right aligned buttons has their own little background. Just 3 little things:

- Compile button and run button seems to have swapped functionality :P
- Do you think the title of the example can be slightly less bold? Currently it looks like a really prominent element on the whole page.
- Can we remove the letter prefixes in the auto-complete dropdown for now? Since they're not doing anything...

Overall I think this is looking just beautiful :D Thanks so much!

**Comment by antfu** [comment]
> Do you think the title of the example can be slightly less bold? Currently it looks like a really prominent element on the whole page.

Should we remove the "文言" title as well?
image
image

> Can we remove the letter prefixes in the auto-complete dropdown for now? Since they're not doing anything...

No problem. I will make it better on the next PR.

**Comment by antfu** [comment]
Done. I also added `touchmove` for handlers in order to work better with mobile devices. :)

**Comment by antfu** [comment]
BTW, I think ide2 is pretty robust now. When should we move it to the default ide?

**Comment by LingDong-** [comment]
Great! I agree we can remove the 文言 text too.

Wonder if we can change the text "Explorer" to 文言, this way the page still has a "title", and because of the fact that the explorer is an explorer is self evident :)

Yeah let's promote it to be the default IDE 🚀! Perhaps we can rename the old IDE to `/old_ide`, and alias `ide2` to `ide`

**Comment by antfu** [comment]
Sure! I will make the migration in this PR then. Would you like the split the CSS/JS as well?

**Comment by LingDong-** [comment]
Sure! Let's split the files and be neat :)

**Comment by antfu** [comment]
Done. I also add a help panel linking to the old ide.

image

**Comment by LingDong-** [comment]
Awesome 👍
Thanks for the great work

**Pull request merged**
