### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kaiyuan01**

### CODE REVIEW

**Comment by LingDong-** [comment]
rin => run
wanted => want/would like
code repo => repo

You need an auto spellchecker :)

**Comment by antfu** [comment]
@kaiyuan01 Hi. I would suggest we utilize the markdown formats to better present our contents. Here are some examples from Github official guide you can refer to.

https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md
https://github.com/rails/rails/blob/master/CONTRIBUTING.md

https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by kaiyuan01** [comment]
Made the change, ran into those build issues:

10:37:36 PM: Executing user command: npm run build:site
10:37:37 PM: npm
10:37:37 PM: ERR!
10:37:37 PM:  missing script: build:site
10:37:37 PM: npm
10:37:37 PM: ERR!

**Comment by LingDong-** [comment]
Tests L❌❌❌TM? Netlify seems to be complaining for some strange reason. :P

**Comment by antfu** [comment]
This PR only create a md file. I think the test failed issue seems not related to the PR itself. Probably something less important gets wrong. 🤔

**Pull request merged**
